let express = require('express');
let router = express.Router();

router.get('/wrike', function (req, res) {
  let companies = [
    {
      name: "2Nova Interactive",
      time: "2 years and 2 months"
    },
    {
      name: "Smeshariki (New Media)",
      time: "9 months"
    },
    {
      name: "Kosmos",
      time: "3 months"
    },
    {
      name: "Logrus",
      time: "several months"
    },
    {
      name: "Восстания 6",
      time: "2 years"
    }
  ];
  let projects = [
    {
      name: "Crocodile Online Game",
      client: "Lipton",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "Rules: One player should draw word generated by app. Other player should guess what word has imaged. 2.8 million unique register gamers in social networks!",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "6 months"
    },
    {
      name: "LaFleur Lottery Game",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "App provides 2 dimensional array of elements. 1000x1000 items. There exist prizes among them, i.e. Samsung smart phone. If you are lucky, you will choose one of the elements which contains prize.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Samsung Galaxy S3 Detective Game Lottery",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "I created in collaboration with another client-side programmer Samsung S3 phone emulator. Every day phone information content is changed, e.g. photos, text messages, e-mails. Social networks users have to guess the phone owner, e.g. Peter Pen, Dr. Watson and others famous persons.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Figure Skating Sochi Olympic Games",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "There was controller on android device. Gamer interacts with it and as a result draw figures on computer screen",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Olympic Video Wishes",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "Users could make video with their web-cams, and sent them to server. Afterwards everyone who uses this app could watch video. Videos contained wishes for olypmic sportsmen.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "3 weeks"
    },
    {
      name: "Intel Detect Emotions",
      client: "Intel",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web",
      project_description: "Flash application. HUD covers youtube player showing information.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "App logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Bitbucket client",
      client: "2Nova Interactive",
      used_technology: "iOS, Objective-C",
      my_role: "Client-side Programmer",
      team_size: "1 people",
      platforms: "Mobile",
      project_description: "These app lets people watch commit log on Bitbucket via iPhone.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "2 weeks"
    },
    {
      name: "iPad photo client for digital marketing event",
      client: "2Nova Interactive",
      used_technology: "iOS, Objective-C",
      my_role: "Client-side Programmer",
      team_size: "1 people",
      platforms: "Mobile",
      project_description: "You could take photo with famous person.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "1 week"
    },
    {
      name: "Online shop, drugstores on map",
      client: "Fialka drugstore net",
      used_technology: "iOS, Objective-C",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Mobile",
      project_description: "You could buy products and observe shops locations. Find the nearest shop to your current location.",
      what_i_have_done: [
        "GUI programming",
        "Map",
        "OOP architecture"
      ],
      duration: "2 months"
    },
    {
      name: "Quest games for children",
      client: "Smeshariki (New Media)",
      used_technology: "Flash, ActionScript 2.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web",
      project_description: "Integrate graphic and animation resources to quest engine. Develop new games from scratch (Zuma)",
      what_i_have_done: [
        "Create different games"
      ],
      duration: "9 months"
    },
    {
      name: "Solitaire (Косынка)",
      client: "Kosmos",
      used_technology: "Flash, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web",
      project_description: "Social card game",
      what_i_have_done: [
        "Connect different social networks APIs to post on the wall",
        "Optimize GUI performance"
      ],
      duration: "3 months"
    },
    {
      name: "Localize games on different languages",
      client: "Logrus",
      used_technology: "Adobe Scripting, JS, Cocos2D",
      my_role: "Integrate, Automation process",
      team_size: "1 people",
      platforms: "Web",
      project_description: "Translate game on 5-7 languages. There were plenty games.",
      what_i_have_done: [
        "Script Adobe Photoshop, Adobe Animate to do drudgery things on JS"
      ],
      duration: "3 months"
    },
    {
      name: "Navigator",
      client: "Восстания 6",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "1-2 people",
      platforms: "Desktop, Tablet",
      project_description: "Observe yourself and company employees on map.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "2 years"
    },
    {
      name: "Regata player",
      client: "Восстания 6",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "1-2 people",
      platforms: "Web, iOS, Android",
      project_description: "This app show how boats have sailed on regata race.",
      what_i_have_done: [
        "Rewrite legacy code",
        "Add new features",
        "Algorithms",
        "GUI programming",
        "OOP architecture",
        "Writing unit tests",
        "Manage junior developer"
      ],
      duration: "2 years"
    },
    {
      name: "JS Regata player",
      client: "Восстания 6",
      used_technology: "JS",
      my_role: "Client-side Programmer",
      team_size: "1 people",
      platforms: "Web",
      project_description: "This app show how boats have sailed on regata race.",
      what_i_have_done: [
        "Rewrite legacy code",
        "Add new features",
        "Algorithms",
        "GUI programming",
        "OOP architecture"
      ],
      duration: "6 months"
    }
  ];

  let languages = [
    "Java", "C", "Objective C", "ActionScript 2.0", "ActionScript 3.0", "JS", "HTML", "CSS"
  ];

  let education = [
    {
      img: "/imgs/suai_logo.png",
      name: "Saint-Petersburg State University of Aerospace Instrumentation (college)",
      faculty: "Computer Systems and Networks",
      year: "2008"
    },
    {
      img: "/imgs/politech_logo.png",
      name: "St. Petersburg State Polytechnic University",
      faculty: "Faculty Of Engineering Cybernetic",
      year: "2014"
    }
  ];

  let instruments = [
    "SASS", "BEM",
    "Grunt", "Gulp", "Ant",
    "npm", "NodeJS", "Express",
    "Handlebars", "React",
    "ECMAScript 6", "Babel",
    "Shell Scripts", "Linux Terminal",
    "Vim", "Webstorm",
    "GIT",
    "Mocha", "Chai",
    "OpenLayers 4"
  ];
  let patterns = [
    "Singleton",
    "Strategy",
    "Decorator",
    "Adapter",
    "Facade",
    "Proxy",
    "MVC",
    "MVP",
    "Builder"
  ];
  res.render('cv', {
    title: 'CV for Wrike',
    styles: '<link rel="stylesheet" href="/css/cv.css">',
    data: {companies, projects, languages, education, instruments, patterns, updateAt: "2018-01-22"},
    layout: false
  });
});

module.exports = router;