let express = require('express');
let router = express.Router();

router.get('/wrike', function (req, res) {
  let companies = [
    {
      name: "2Nova Interactive",
      time: "2 years and 2 months"
    },
    {
      name: "Smeshariki (New Media)",
      time: "9 months"
    },
    {
      name: "Восстания 6",
      time: "2 years"
    }
  ];
  let projects = [
    {
      name: "Crocodile Online Game",
      client: "Lipton",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "Rules: One player should draw word generated by app. Other player should guess what word has imaged. 2.8 million unique register gamers in social networks!",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "6 months"
    },
    {
      name: "LaFleur Lottery Game",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "App provides 2 dimensional array of elements. 1000x1000 items. There exist prizes among them, i.e. Samsung smart phone. If you are lucky, you will choose one of the elements which contains prize.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Samsung Galaxy S3 Detective Game Lottery",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "I created in collaboration with another client-side programmer Samsung S3 phone emulator. Every day phone information content is changed, e.g. photos, text messages, e-mails. Social networks users have to guess the phone owner, e.g. Peter Pen, Dr. Watson and others famous persons.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Figure Skating Sochi Olympic Games",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "3 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "There was controller on android device. Gamer interacts with it and as a result draw figures on computer screen",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "Game logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Olympic Video Wishes",
      client: "Samsung",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web Social Networks - Facebook, VK, OK",
      project_description: "Users could make video with their web-cams, and sent them to server. Afterwards everyone who uses this app could watch video. Videos contained wishes for olypmic sportsmen.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "3 weeks"
    },
    {
      name: "Intel Detect Emotions",
      client: "Intel",
      used_technology: "Flash platform, ActionScript 3.0",
      my_role: "Client-side Programmer",
      team_size: "2 people",
      platforms: "Web",
      project_description: "Flash application. HUD covers youtube player showing information.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture",
        "App logic"
      ],
      duration: "3 weeks"
    },
    {
      name: "Bitbucket client",
      client: "2Nova Interactive",
      used_technology: "iOS, Objective-C",
      my_role: "Client-side Programmer",
      team_size: "1 people",
      platforms: "Mobile",
      project_description: "These app lets people watch commit log on Bitbucket via iPhone.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "2 weeks"
    },
    {
      name: "iPad photo client for digital marketing event",
      client: "2Nova Interactive",
      used_technology: "iOS, Objective-C",
      my_role: "Client-side Programmer",
      team_size: "1 people",
      platforms: "Mobile",
      project_description: "You could take photo with famous person.",
      what_i_have_done: [
        "GUI programming",
        "OOP architecture"
      ],
      duration: "1 week"
    }
  ];
  let languages = [
    "ActionScript 2.0", "ActionScript 3.0", "Objective C", "JS"
  ];
  res.render('cv', {
    title: 'CV for Wrike',
    styles: '<link rel="stylesheet" href="/css/cv.css">',
    data: {companies, projects, languages},
    layout: false
  });
});

module.exports = router;